import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import WorkoutContext from "@/Context/WorkoutContext";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
   <html lang="en" data-theme="white">
      <body className="min-h-screen flex flex-col bg-black">
      <WorkoutContext>
         <Navbar />

        <main className="flex-1">
          {children}
        </main>

        <Footer />
        <ToastContainer/>
        <Toaster  position="top-right" reverseOrder={false}/>
      </WorkoutContext>
      </body>
    </html>
  );
}
